package anthropic

import gollmx "github.com/onlyhyde/gollm-x"

// AnthropicModels defines the available Anthropic models
var AnthropicModels = []gollmx.Model{
	{
		ID:            "claude-3-5-sonnet-20241022",
		Name:          "Claude 3.5 Sonnet",
		Provider:      ProviderID,
		ContextWindow: 200000,
		MaxOutput:     8192,
		InputPrice:    3.00,
		OutputPrice:   15.00,
		Features: []gollmx.Feature{
			gollmx.FeatureChat,
			gollmx.FeatureStreaming,
			gollmx.FeatureVision,
			gollmx.FeatureTools,
			gollmx.FeatureJSON,
			gollmx.FeatureSystemPrompt,
		},
	},
	{
		ID:            "claude-3-5-haiku-20241022",
		Name:          "Claude 3.5 Haiku",
		Provider:      ProviderID,
		ContextWindow: 200000,
		MaxOutput:     8192,
		InputPrice:    1.00,
		OutputPrice:   5.00,
		Features: []gollmx.Feature{
			gollmx.FeatureChat,
			gollmx.FeatureStreaming,
			gollmx.FeatureVision,
			gollmx.FeatureTools,
			gollmx.FeatureJSON,
			gollmx.FeatureSystemPrompt,
		},
	},
	{
		ID:            "claude-3-opus-20240229",
		Name:          "Claude 3 Opus",
		Provider:      ProviderID,
		ContextWindow: 200000,
		MaxOutput:     4096,
		InputPrice:    15.00,
		OutputPrice:   75.00,
		Features: []gollmx.Feature{
			gollmx.FeatureChat,
			gollmx.FeatureStreaming,
			gollmx.FeatureVision,
			gollmx.FeatureTools,
			gollmx.FeatureJSON,
			gollmx.FeatureSystemPrompt,
		},
	},
	{
		ID:            "claude-3-sonnet-20240229",
		Name:          "Claude 3 Sonnet",
		Provider:      ProviderID,
		ContextWindow: 200000,
		MaxOutput:     4096,
		InputPrice:    3.00,
		OutputPrice:   15.00,
		Features: []gollmx.Feature{
			gollmx.FeatureChat,
			gollmx.FeatureStreaming,
			gollmx.FeatureVision,
			gollmx.FeatureTools,
			gollmx.FeatureJSON,
			gollmx.FeatureSystemPrompt,
		},
	},
	{
		ID:            "claude-3-haiku-20240307",
		Name:          "Claude 3 Haiku",
		Provider:      ProviderID,
		ContextWindow: 200000,
		MaxOutput:     4096,
		InputPrice:    0.25,
		OutputPrice:   1.25,
		Features: []gollmx.Feature{
			gollmx.FeatureChat,
			gollmx.FeatureStreaming,
			gollmx.FeatureVision,
			gollmx.FeatureTools,
			gollmx.FeatureJSON,
			gollmx.FeatureSystemPrompt,
		},
	},
}
