package openai

import gollmx "github.com/onlyhyde/gollm-x"

// OpenAIModels contains all known OpenAI models
var OpenAIModels = []gollmx.Model{
	// GPT-4o series
	{
		ID:            "gpt-4o",
		Name:          "GPT-4o",
		Provider:      ProviderID,
		Description:   "Most advanced multimodal model, great for complex tasks",
		ContextWindow: 128000,
		MaxOutput:     16384,
		InputPrice:    2.50,
		OutputPrice:   10.00,
		Features: []gollmx.Feature{
			gollmx.FeatureChat,
			gollmx.FeatureStreaming,
			gollmx.FeatureVision,
			gollmx.FeatureTools,
			gollmx.FeatureJSON,
			gollmx.FeatureSystemPrompt,
		},
		ReleaseDate: "2024-05-13",
	},
	{
		ID:            "gpt-4o-mini",
		Name:          "GPT-4o Mini",
		Provider:      ProviderID,
		Description:   "Affordable, fast model for lightweight tasks",
		ContextWindow: 128000,
		MaxOutput:     16384,
		InputPrice:    0.15,
		OutputPrice:   0.60,
		Features: []gollmx.Feature{
			gollmx.FeatureChat,
			gollmx.FeatureStreaming,
			gollmx.FeatureVision,
			gollmx.FeatureTools,
			gollmx.FeatureJSON,
			gollmx.FeatureSystemPrompt,
		},
		ReleaseDate: "2024-07-18",
	},
	// GPT-4 Turbo
	{
		ID:            "gpt-4-turbo",
		Name:          "GPT-4 Turbo",
		Provider:      ProviderID,
		Description:   "Previous flagship model with vision capabilities",
		ContextWindow: 128000,
		MaxOutput:     4096,
		InputPrice:    10.00,
		OutputPrice:   30.00,
		Features: []gollmx.Feature{
			gollmx.FeatureChat,
			gollmx.FeatureStreaming,
			gollmx.FeatureVision,
			gollmx.FeatureTools,
			gollmx.FeatureJSON,
			gollmx.FeatureSystemPrompt,
		},
		ReleaseDate: "2024-04-09",
	},
	// GPT-4
	{
		ID:            "gpt-4",
		Name:          "GPT-4",
		Provider:      ProviderID,
		Description:   "Original GPT-4 model",
		ContextWindow: 8192,
		MaxOutput:     8192,
		InputPrice:    30.00,
		OutputPrice:   60.00,
		Features: []gollmx.Feature{
			gollmx.FeatureChat,
			gollmx.FeatureStreaming,
			gollmx.FeatureTools,
			gollmx.FeatureJSON,
			gollmx.FeatureSystemPrompt,
		},
		ReleaseDate: "2023-03-14",
	},
	// GPT-3.5
	{
		ID:            "gpt-3.5-turbo",
		Name:          "GPT-3.5 Turbo",
		Provider:      ProviderID,
		Description:   "Fast, inexpensive model for simple tasks",
		ContextWindow: 16385,
		MaxOutput:     4096,
		InputPrice:    0.50,
		OutputPrice:   1.50,
		Features: []gollmx.Feature{
			gollmx.FeatureChat,
			gollmx.FeatureStreaming,
			gollmx.FeatureTools,
			gollmx.FeatureJSON,
			gollmx.FeatureSystemPrompt,
		},
		ReleaseDate: "2022-11-30",
	},
	// o1 series (reasoning)
	{
		ID:            "o1",
		Name:          "o1",
		Provider:      ProviderID,
		Description:   "Reasoning model for complex tasks",
		ContextWindow: 200000,
		MaxOutput:     100000,
		InputPrice:    15.00,
		OutputPrice:   60.00,
		Features: []gollmx.Feature{
			gollmx.FeatureChat,
			gollmx.FeatureStreaming,
			gollmx.FeatureVision,
			gollmx.FeatureTools,
		},
		ReleaseDate: "2024-12-05",
	},
	{
		ID:            "o1-mini",
		Name:          "o1 Mini",
		Provider:      ProviderID,
		Description:   "Faster reasoning model, optimized for coding and STEM",
		ContextWindow: 128000,
		MaxOutput:     65536,
		InputPrice:    3.00,
		OutputPrice:   12.00,
		Features: []gollmx.Feature{
			gollmx.FeatureChat,
			gollmx.FeatureStreaming,
		},
		ReleaseDate: "2024-09-12",
	},
	// Embedding models
	{
		ID:            "text-embedding-3-large",
		Name:          "Text Embedding 3 Large",
		Provider:      ProviderID,
		Description:   "Most capable embedding model for text similarity",
		ContextWindow: 8191,
		InputPrice:    0.13,
		Features: []gollmx.Feature{
			gollmx.FeatureEmbedding,
		},
		ReleaseDate: "2024-01-25",
	},
	{
		ID:            "text-embedding-3-small",
		Name:          "Text Embedding 3 Small",
		Provider:      ProviderID,
		Description:   "Small and efficient embedding model",
		ContextWindow: 8191,
		InputPrice:    0.02,
		Features: []gollmx.Feature{
			gollmx.FeatureEmbedding,
		},
		ReleaseDate: "2024-01-25",
	},
	{
		ID:            "text-embedding-ada-002",
		Name:          "Text Embedding Ada 002",
		Provider:      ProviderID,
		Description:   "Previous generation embedding model",
		ContextWindow: 8191,
		InputPrice:    0.10,
		Features: []gollmx.Feature{
			gollmx.FeatureEmbedding,
		},
		Deprecated:  true,
		ReleaseDate: "2022-12-15",
	},
}
